language: php

php:
  - 5.6
  - 7.0
  - nightly
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
    - php: nightly
  
install:
  - curl -s http://getcomposer.org/installer | php -d date.timezone="Europe/Berlin" -- --install-dir=./bin/
  - ./bin/composer.phar install

script: ./bin/composer.phar build

after_script: php vendor/bin/coveralls -v

notifications:
  irc:
    channels:
      - "chat.freenode.net#honeeybee"
    on_success: always
    on_failure: always
    use_notice: false
    skip_join: false
